[package]
name = "bowl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
glfw = "0.45.0"
glam = "0.21.3"
backtrace = "0.3.66"

[dev-dependencies]
rand = "0.8.5"